In [1]:
import pdblp
import pandas as pd 
import warnings
warnings.filterwarnings("ignore")

In [2]:
pricetkr = ['SPX Index',
 'CCMP Index',
 'CL1 COMB Comdty',
 'HG1 COMB Comdty',
 'INDU Index',
 'SXXP Index',
 'SHCOMP Index',
 'LBUSTRUU Index',
 'LF98TRUU Index',
 'NG1 COMB Comdty',
 'XAU Curncy']
macrotkr = ['CSIIGL Index',
 'WRAIRISK Index',
 'VIX Index',
 'USGG10YR Index',
 'XAU BGN Curncy',
 'GSUSFCI Index',
 'GSCNFCI Index',
 'GSGLCAI Index',
 'GSUSCAI Index',
 'GSCNCAI Index',
 'FEDL01 Index']

In [3]:
con = pdblp.BCon(debug=False, port=8194, timeout=5000)
con.start()
macrodf = con.bdh(macrotkr,'PX_LAST',
                '19500629', '22000630')
pricedf = con.bdh(pricetkr,'PX_LAST',
                '19500629', '22000630')

In [4]:
macrodf.to_csv('sy_macro.csv')
pricedf.to_csv('sy_price.csv')

In [5]:
macrodf

ticker,CSIIGL Index,GSUSCAI Index,GSCNCAI Index,WRAIRISK Index,VIX Index,FEDL01 Index,USGG10YR Index,XAU BGN Curncy,GSUSFCI Index,GSCNFCI Index,GSGLCAI Index
field,PX_LAST,PX_LAST,PX_LAST,PX_LAST,PX_LAST,PX_LAST,PX_LAST,PX_LAST,PX_LAST,PX_LAST,PX_LAST
date,,,,,,,,,,,
1950-06-30,NaN,NaN,NaN,NaN,NaN,NaN,NaN,34.72,NaN,NaN,NaN
1950-07-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,34.72,NaN,NaN,NaN
1950-08-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,34.72,NaN,NaN,NaN
1950-09-29,NaN,NaN,NaN,NaN,NaN,NaN,NaN,34.72,NaN,NaN,NaN
1950-10-31,NaN,NaN,NaN,NaN,NaN,NaN,NaN,34.72,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
2020-11-24,NaN,NaN,NaN,NaN,21.64,0.08,0.8799,1807.59,97.83,102.79,NaN
2020-11-25,NaN,NaN,NaN,NaN,21.25,0.08,0.8816,1807.56,97.83,102.62,NaN
2020-11-26,NaN,NaN,NaN,NaN,NaN,NaN,0.8816,1815.80,NaN,NaN,NaN
2020-11-27,NaN,NaN,NaN,NaN,20.84,NaN,0.8373,1787.79,NaN,NaN,NaN
2020-11-30,NaN,NaN,NaN,NaN,NaN,NaN,0.8422,1783.20,NaN,NaN,NaN

In [6]:
pricedf

ticker,LF98TRUU Index,SPX Index,NG1 COMB Comdty,CCMP Index,XAU Curncy,CL1 COMB Comdty,HG1 COMB Comdty,INDU Index,SXXP Index,SHCOMP Index,LBUSTRUU Index
field,PX_LAST,PX_LAST,PX_LAST,PX_LAST,PX_LAST,PX_LAST,PX_LAST,PX_LAST,PX_LAST,PX_LAST,PX_LAST
date,,,,,,,,,,,
1950-06-29,NaN,17.44,NaN,NaN,NaN,NaN,NaN,206.70,NaN,NaN,NaN
1950-06-30,NaN,17.69,NaN,NaN,34.72,NaN,NaN,209.10,NaN,NaN,NaN
1950-07-03,NaN,17.64,NaN,NaN,NaN,NaN,NaN,208.30,NaN,NaN,NaN
1950-07-05,NaN,17.81,NaN,NaN,NaN,NaN,NaN,210.00,NaN,NaN,NaN
1950-07-06,NaN,17.91,NaN,NaN,NaN,NaN,NaN,210.80,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
2020-11-24,2290.75,3635.41,2.775,12036.79,1807.59,44.91,329.95,30046.24,392.39,3402.823,2382.54
2020-11-25,2291.96,3629.65,2.896,12094.40,1807.56,45.71,330.95,29872.47,392.09,3362.327,2382.19
2020-11-26,NaN,NaN,NaN,NaN,1815.80,NaN,NaN,NaN,391.63,3369.733,NaN
2020-11-27,2293.18,3638.35,2.843,12205.85,1787.79,45.53,339.95,29910.37,393.23,3408.307,2387.01
2020-11-30,NaN,NaN,2.884,NaN,1783.30,45.22,340.90,NaN,NaN,NaN,NaN